import { SceneGraph } from '../../video-engine/src/core/types'

export interface ExplainerParams {
  problem: string
  solution: string
  steps: string[]
  brandColor: string
  cta?: string
}

export function createExplainer(params: ExplainerParams): Partial<SceneGraph> {
  return {
    scenes: [
      {
        id: 'problem',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
          preset: 'slow-pull-back',
        },
        nodes: [
          {
            id: 'problem-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'vignette', params: { intensity: 0.6 }, order: 0 }],
            metadata: { color: '#1A0000' },
          },
          {
            id: 'problem-label',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -80 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 15, value: 0.6 }] },
            ],
            effects: [],
            metadata: { content: 'THE PROBLEM', fontSize: 18, fontWeight: 600, color: params.brandColor, letterSpacing: 4 },
          },
          {
            id: 'problem-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: -100, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '75%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 25, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 0, value: [-100, 0] }, { frame: 25, value: [0, 0] }] },
            ],
            effects: [],
            metadata: { content: params.problem, fontSize: 42, fontWeight: 700, color: '#fff' },
          },
        ],
      },
      {
        id: 'solution',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'solution-bg',
            type: 'gradient',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'bloom', params: { intensity: 0.15 }, order: 0 }],
            metadata: { colors: ['#000000', params.brandColor], angle: 45 },
          },
          {
            id: 'solution-label',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -80 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 15, value: 0.6 }] },
            ],
            effects: [],
            metadata: { content: 'OUR SOLUTION', fontSize: 18, fontWeight: 600, color: '#fff', letterSpacing: 4 },
          },
          {
            id: 'solution-icon',
            type: 'shape',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -30 }, rotation: 0, scale: { x: 0, y: 0 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 10, value: [0, 0] }, { frame: 25, value: [1, 1] }] },
              { property: 'rotation', keyframes: [{ frame: 10, value: -180 }, { frame: 25, value: 0 }] },
            ],
            effects: [],
            metadata: { shape: 'circle', size: 48, fillColor: params.brandColor },
          },
          {
            id: 'solution-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 40 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '70%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 15, value: 0 }, { frame: 35, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 15, value: [0, 60] }, { frame: 35, value: [0, 40] }] },
            ],
            effects: [],
            metadata: { content: params.solution, fontSize: 38, fontWeight: 700, color: '#fff' },
          },
        ],
      },
      ...params.steps.map((step, i) => ({
        id: `step-${i}`,
        duration: 4,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
          preset: i % 2 === 0 ? 'pan-right' : 'pan-left',
        },
        nodes: [
          {
            id: `step-bg-${i}`,
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 10, value: 1 }] },
            ],
            effects: [],
            metadata: { color: i % 2 === 0 ? '#0D0D0D' : '#161616' },
          },
          {
            id: `step-number-${i}`,
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: -300, y: -60 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 20, value: 0.15 }] },
              { property: 'position', keyframes: [{ frame: 0, value: [-300, -60] }, { frame: 20, value: [-200, -60] }] },
            ],
            effects: [],
            metadata: { content: `0${i + 1}`, fontSize: 120, fontWeight: 900, color: params.brandColor },
          },
          {
            id: `step-title-${i}`,
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: -20 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '65%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 10, value: 0 }, { frame: 30, value: 1 }] },
              { property: 'scale', keyframes: [{ frame: 10, value: [0.9, 0.9] }, { frame: 30, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { content: step, fontSize: 40, fontWeight: 700, color: '#fff' },
          },
          {
            id: `step-line-${i}`,
            type: 'rect',
            children: [],
            parent: `step-title-${i}`,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 45 }, rotation: 0, scale: { x: 0, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center', maxWidth: '30%' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 30, value: [0, 1] }, { frame: 45, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { color: params.brandColor, height: 3, borderRadius: 2 },
          },
        ],
      })),
      {
        id: 'outro',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'outro-bg',
            type: 'gradient',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'bloom', params: { intensity: 0.2 }, order: 0 }],
            metadata: { colors: [params.brandColor, '#000000'] },
          },
          {
            id: 'outro-cta',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 20, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 0, value: [0, 40] }, { frame: 20, value: [0, 0] }] },
            ],
            effects: [],
            metadata: {
              content: params.cta ?? 'Get Started Today',
              fontSize: 52,
              fontWeight: 800,
              color: '#fff',
            },
          },
          {
            id: 'outro-sub',
            type: 'text',
            children: [],
            parent: 'outro-cta',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 70 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 20, value: 0 }, { frame: 40, value: 0.7 }] },
            ],
            effects: [],
            metadata: { content: 'No commitment. Start free.', fontSize: 20, fontWeight: 400, color: 'rgba(255,255,255,0.6)' },
          },
        ],
      },
    ],
  }
}
