import { SceneGraph } from '../../video-engine/src/core/types'

export interface FeatureUpdateParams {
  version: string
  featureName: string
  description: string
  changes: string[]
  impact: string
  brandColor: string
}

export function createFeatureUpdate(params: FeatureUpdateParams): Partial<SceneGraph> {
  return {
    scenes: [
      {
        id: 'badge',
        duration: 2,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'badge-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [],
            metadata: { color: '#050505' },
          },
          {
            id: 'badge-pill',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 0, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 0, value: [0, 1] }, { frame: 20, value: [1, 1] }] },
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 5, value: 1 }, { frame: 40, value: 1 }, { frame: 55, value: 0 }] },
            ],
            effects: [{ type: 'glow', params: { color: params.brandColor, intensity: 0.4, radius: 20 }, order: 0 }],
            metadata: { color: params.brandColor, width: 140, height: 40, borderRadius: 20 },
          },
          {
            id: 'badge-text',
            type: 'text',
            children: [],
            parent: 'badge-pill',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 5, value: 0 }, { frame: 15, value: 1 }, { frame: 50, value: 1 }, { frame: 55, value: 0 }] },
            ],
            effects: [],
            metadata: { content: `NEW IN ${params.version}`, fontSize: 14, fontWeight: 800, color: '#fff', letterSpacing: 3 },
          },
        ],
      },
      {
        id: 'feature-name',
        duration: 2.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'feature-name-bg',
            type: 'gradient',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'bloom', params: { intensity: 0.2 }, order: 0 }],
            metadata: { colors: ['#000000', params.brandColor], angle: 90 },
          },
          {
            id: 'feature-name-divider',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -100 }, rotation: 0, scale: { x: 0, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '15%' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 0, value: [0, 1] }, { frame: 15, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { color: params.brandColor, height: 4, borderRadius: 2 },
          },
          {
            id: 'feature-name-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '80%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 5, value: 0 }, { frame: 25, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 5, value: [0, 30] }, { frame: 25, value: [0, 0] }] },
            ],
            effects: [],
            metadata: { content: params.featureName, fontSize: 52, fontWeight: 800, color: '#fff' },
          },
          {
            id: 'feature-name-desc',
            type: 'text',
            children: [],
            parent: 'feature-name-text',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 70 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center', maxWidth: '65%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 20, value: 0 }, { frame: 40, value: 0.7 }] },
            ],
            effects: [],
            metadata: { content: params.description, fontSize: 20, fontWeight: 400, color: 'rgba(255,255,255,0.7)' },
          },
        ],
      },
      {
        id: 'changes',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
          preset: 'slow-pan',
        },
        nodes: [
          {
            id: 'changes-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [],
            metadata: { color: '#0A0A0A' },
          },
          {
            id: 'changes-heading',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -220 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 15, value: 0.6 }] },
            ],
            effects: [],
            metadata: { content: 'WHAT\'S CHANGED', fontSize: 16, fontWeight: 600, color: params.brandColor, letterSpacing: 4 },
          },
          ...params.changes.map((change, i) => ({
            id: `change-item-${i}`,
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: -150, y: -100 + i * 80 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'start', maxWidth: '65%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 10 + i * 10, value: 0 }, { frame: 30 + i * 10, value: 1 }] },
              { property: 'position', keyframes: [
                { frame: 10 + i * 10, value: [-200, -100 + i * 80] },
                { frame: 30 + i * 10, value: [-150, -100 + i * 80] },
              ] },
            ],
            effects: [],
            metadata: { content: `→ ${change}`, fontSize: 22, fontWeight: 500, color: '#fff' },
          })),
        ],
      },
      {
        id: 'impact',
        duration: 2.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'impact-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'bloom', params: { intensity: 0.15 }, order: 0 }],
            metadata: { color: params.brandColor },
          },
          {
            id: 'impact-icon',
            type: 'shape',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -80 }, rotation: 0, scale: { x: 0, y: 0 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 0, value: [0, 0] }, { frame: 15, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { shape: 'circle', size: 64, fillColor: 'rgba(255,255,255,0.2)' },
          },
          {
            id: 'impact-icon-inner',
            type: 'text',
            children: [],
            parent: 'impact-icon',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 5, value: 0 }, { frame: 20, value: 1 }] },
            ],
            effects: [],
            metadata: { content: '⚡', fontSize: 32, fontWeight: 400, color: '#fff' },
          },
          {
            id: 'impact-text',
            type: 'text',
            children: [],
            parent: 'impact-icon',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 90 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center', maxWidth: '75%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 10, value: 0 }, { frame: 30, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 10, value: [0, 110] }, { frame: 30, value: [0, 90] }] },
            ],
            effects: [],
            metadata: { content: params.impact, fontSize: 32, fontWeight: 700, color: '#fff' },
          },
        ],
      },
    ],
  }
}
