import { SceneGraph } from '../../video-engine/src/core/types'

export interface LaunchTeaserParams {
  productName: string
  tagline: string
  launchDate: string
  brandColor: string
  logoUrl?: string
}

export function createLaunchTeaser(params: LaunchTeaserParams): Partial<SceneGraph> {
  return {
    scenes: [
      {
        id: 'countdown',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'countdown-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [],
            metadata: { color: '#000000' },
          },
          {
            id: 'countdown-number',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [
                { frame: 0, value: 1 }, { frame: 28, value: 1 }, { frame: 30, value: 0 },
              ] },
              { property: 'scale', keyframes: [
                { frame: 0, value: [1.2, 1.2] }, { frame: 10, value: [1, 1] },
                { frame: 20, value: [1.2, 1.2] }, { frame: 28, value: [1.5, 1.5] },
              ] },
            ],
            effects: [{ type: 'glow', params: { color: params.brandColor, intensity: 0.5, radius: 40 }, order: 0 }],
            metadata: { content: '3', fontSize: 180, fontWeight: 900, color: '#fff' },
          },
          {
            id: 'countdown-sub',
            type: 'text',
            children: [],
            parent: 'countdown-number',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 110 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0.5 }, { frame: 28, value: 0 }] },
            ],
            effects: [],
            metadata: { content: 'Something big is coming...', fontSize: 18, fontWeight: 400, color: 'rgba(255,255,255,0.4)' },
          },
        ],
      },
      {
        id: 'flash',
        duration: 0.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'flash-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [
              { property: 'opacity', keyframes: [
                { frame: 0, value: 1 }, { frame: 3, value: 1 }, { frame: 10, value: 0 },
              ] },
            ],
            effects: [],
            metadata: { color: params.brandColor },
          },
        ],
      },
      {
        id: 'logo-reveal',
        duration: 2.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'logo-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'vignette', params: { intensity: 0.4 }, order: 0 }],
            metadata: { color: '#000000' },
          },
          {
            id: 'logo',
            type: params.logoUrl ? 'image' : 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -30 }, rotation: 0, scale: { x: 0, y: 0 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'scale', keyframes: [{ frame: 0, value: [0, 0] }, { frame: 15, value: [0.8, 0.8] }, { frame: 25, value: [1, 1] }] },
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 5, value: 1 }] },
            ],
            effects: [{ type: 'glow', params: { color: params.brandColor, intensity: 0.3, radius: 30 }, order: 0 }],
            metadata: params.logoUrl
              ? { src: params.logoUrl, width: 200, height: 60, fit: 'contain' }
              : { content: params.productName, fontSize: 56, fontWeight: 800, color: '#fff' },
          },
          {
            id: 'logo-tagline',
            type: 'text',
            children: [],
            parent: 'logo',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 70 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center', maxWidth: '70%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 20, value: 0 }, { frame: 40, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 20, value: [0, 90] }, { frame: 40, value: [0, 70] }] },
            ],
            effects: [],
            metadata: { content: params.tagline, fontSize: 24, fontWeight: 400, color: 'rgba(255,255,255,0.6)' },
          },
        ],
      },
      {
        id: 'date',
        duration: 2.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
          preset: 'dramatic-zoom',
        },
        nodes: [
          {
            id: 'date-bg',
            type: 'gradient',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'bloom', params: { intensity: 0.25 }, order: 0 }],
            metadata: { colors: ['#000000', params.brandColor] },
          },
          {
            id: 'date-label',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -60 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 20, value: 0.6 }] },
            ],
            effects: [],
            metadata: { content: 'LAUNCHING', fontSize: 20, fontWeight: 600, color: params.brandColor, letterSpacing: 6 },
          },
          {
            id: 'date-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 5, value: 0 }, { frame: 25, value: 1 }] },
              { property: 'scale', keyframes: [{ frame: 5, value: [1.3, 1.3] }, { frame: 25, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { content: params.launchDate, fontSize: 48, fontWeight: 800, color: '#fff' },
          },
          {
            id: 'date-reminder',
            type: 'text',
            children: [],
            parent: 'date-text',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 70 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 25, value: 0 }, { frame: 50, value: 0.8 }] },
            ],
            effects: [],
            metadata: { content: 'Set a reminder', fontSize: 18, fontWeight: 400, color: 'rgba(255,255,255,0.5)' },
          },
        ],
      },
    ],
  }
}
