import { SceneGraph } from '../../video-engine/src/core/types'

export interface SocialClipParams {
  hook: string
  content: string
  cta: string
  brandColor: string
  format?: 'square' | 'vertical'
}

export function createSocialClip(params: SocialClipParams): Partial<SceneGraph> {
  const isVertical = params.format === 'vertical'

  return {
    aspectRatio: isVertical ? '9:16' : '1:1',
    resolution: isVertical ? { width: 1080, height: 1920 } : { width: 1080, height: 1080 },
    scenes: [
      {
        id: 'hook',
        duration: 1.5,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
          preset: 'quick-push',
        },
        nodes: [
          {
            id: 'hook-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [],
            metadata: { color: params.brandColor },
          },
          {
            id: 'hook-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: isVertical ? '85%' : '80%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 5, value: 1 }, { frame: 35, value: 1 }, { frame: 45, value: 0 }] },
              { property: 'scale', keyframes: [{ frame: 0, value: [0.7, 0.7] }, { frame: 10, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { content: params.hook, fontSize: 64, fontWeight: 800, color: '#fff', textAlign: 'center' },
          },
        ],
      },
      {
        id: 'content',
        duration: 3,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'content-bg',
            type: 'rect',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [{ type: 'shadow', params: { blur: 30, color: params.brandColor, opacity: 0.3 }, order: 0 }],
            metadata: { color: '#0A0A0A' },
          },
          {
            id: 'content-dot',
            type: 'shape',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -80 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 10, value: 1 }] },
            ],
            effects: [],
            metadata: { shape: 'circle', size: 8, fillColor: params.brandColor },
          },
          {
            id: 'content-text',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 2,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: isVertical ? '85%' : '75%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 5, value: 0 }, { frame: 20, value: 1 }] },
              { property: 'scale', keyframes: [{ frame: 5, value: [0.95, 0.95] }, { frame: 20, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { content: params.content, fontSize: 36, fontWeight: 500, color: '#fff', textAlign: 'center' },
          },
        ],
      },
      {
        id: 'cta',
        duration: 2,
        fps: 30,
        camera: {
          type: 'perspective',
          position: { x: 0, y: 0, z: 0 },
          rotation: { x: 0, y: 0, z: 0 },
          zoom: 1,
          focalLength: 50,
        },
        nodes: [
          {
            id: 'cta-bg',
            type: 'gradient',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', maxWidth: '100%', maxHeight: '100%' },
            animations: [],
            effects: [],
            metadata: { colors: ['#000000', params.brandColor], angle: 135 },
          },
          {
            id: 'cta-main',
            type: 'text',
            children: [],
            parent: null,
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: -20 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center', maxWidth: '80%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 0, value: 0 }, { frame: 15, value: 1 }] },
              { property: 'position', keyframes: [{ frame: 0, value: [0, 30] }, { frame: 15, value: [0, -20] }] },
            ],
            effects: [],
            metadata: { content: params.cta, fontSize: 44, fontWeight: 800, color: '#fff' },
          },
          {
            id: 'cta-btn',
            type: 'rect',
            children: [],
            parent: 'cta-main',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 0,
            transform: { position: { x: 0, y: 65 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'top-center', alignment: 'center', maxWidth: '60%' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 15, value: 0 }, { frame: 30, value: 1 }] },
              { property: 'scale', keyframes: [{ frame: 15, value: [0.8, 0.8] }, { frame: 30, value: [1, 1] }] },
            ],
            effects: [],
            metadata: { color: '#fff', height: 48, borderRadius: 24 },
          },
          {
            id: 'cta-btn-text',
            type: 'text',
            children: [],
            parent: 'cta-btn',
            visible: true,
            blendMode: 'normal',
            opacity: 1,
            zIndex: 1,
            transform: { position: { x: 0, y: 0 }, rotation: 0, scale: { x: 1, y: 1 } },
            constraints: { anchor: 'center', alignment: 'center' },
            animations: [
              { property: 'opacity', keyframes: [{ frame: 20, value: 0 }, { frame: 35, value: 1 }] },
            ],
            effects: [],
            metadata: { content: 'Learn More →', fontSize: 18, fontWeight: 700, color: params.brandColor },
          },
        ],
      },
    ],
  }
}
